---
# tasks file for nomad
- name: Run specified tasks on current platform
  include: "{{ ansible_system }}.yml"
- block:
  - name: Ensure a directory related to daemon scripts exist
    file:
      path: "{{ nomad_daemon_script_dir }}"
      owner: "{{ nomad_owner }}"
      group: "{{ nomad_group }}"
      state: 'directory'
  - name: Ensure directory(for logging related to daemon) exist
    file:
      path: "{{ nomad_daemon_log_dir }}"
      owner: "{{ nomad_owner }}"
      group: "{{ nomad_group }}"
      state: 'directory'
  - name: Check path related to PID file of daemon
    stat:
      path: "{{ nomad_daemon_pid_dir  }}"
    register: stat_daemon_pid_dir
    changed_when: no
  - name: Ensure directory(for lock file of daemon) exist
    file:
      path: "{{ nomad_daemon_pid_dir }}"
      owner: "{{ nomad_owner }}"
      group: "{{ nomad_group }}"
      state: 'directory'
    when: not stat_daemon_pid_dir.stat.exists
  - name: Resolve the dependencies of daemon script
    pip:
      name: "{{ item }}"
    with_items:
      - python-daemon
      - click
  - name: Set daemon scripts
    template:
      src: "daemons.py.j2"
      dest: "{{ nomad_daemon_script_dir }}/daemons.py"
      owner: "{{ nomad_owner }}"
      group: "{{ nomad_group }}"
      mode: '0755'
  become: yes
- block:
  - name: Ensure a directory of Nomad configs exists
    file:
      path: "{{ nomad_config_remote_dir }}"
      owner: "{{ nomad_owner }}"
      group: "{{ nomad_group }}"
      state: 'directory'
  - name: Set a default config file
    template:
     src: 'nomad_common.json.j2'
     dest: "{{ nomad_config_remote_dir }}/nomad_common.json"
     owner: "{{ nomad_owner }}"
     group: "{{ nomad_group }}"
  become: yes
- name: set additional config files
  copy:
    src: "{{ nomad_config_src_dir }}"
    dest: "{{ nomad_config_remote_dir }}"
    owner: "{{ nomad_owner }}"
    group: "{{ nomad_group }}"
  when: nomad_config_src_dir is defined
  become: yes
